import { Personality } from "../../types/ai";

export const PERSONALITIES: Record<string, Personality> = {
  calm: {
    name: "Calm",
    movementSpeedMultiplier: 0.7,
    speechFrequency: 0.15,
    idleChance: 0.6,
    moodChangeRate: 0.8,
    curiosity: 0.3,
    baseMood: "happy",
  },
  energetic: {
    name: "Energetic",
    movementSpeedMultiplier: 1.5,
    speechFrequency: 0.4,
    idleChance: 0.2,
    moodChangeRate: 1.3,
    curiosity: 0.7,
    baseMood: "excited",
  },
  lazy: {
    name: "Lazy",
    movementSpeedMultiplier: 0.5,
    speechFrequency: 0.1,
    idleChance: 0.8,
    moodChangeRate: 0.6,
    curiosity: 0.1,
    baseMood: "sleepy",
  },
  playful: {
    name: "Playful",
    movementSpeedMultiplier: 1.2,
    speechFrequency: 0.3,
    idleChance: 0.3,
    moodChangeRate: 1.1,
    curiosity: 0.6,
    baseMood: "happy",
  },
  curious: {
    name: "Curious",
    movementSpeedMultiplier: 1.1,
    speechFrequency: 0.25,
    idleChance: 0.4,
    moodChangeRate: 1.0,
    curiosity: 0.9,
    baseMood: "curious",
  },
  professional: {
    name: "Professional",
    movementSpeedMultiplier: 0.9,
    speechFrequency: 0.2,
    idleChance: 0.5,
    moodChangeRate: 0.8,
    curiosity: 0.4,
    baseMood: "happy",
  },
  chaotic: {
    name: "Chaotic",
    movementSpeedMultiplier: 1.6,
    speechFrequency: 0.5,
    idleChance: 0.2,
    moodChangeRate: 1.5,
    curiosity: 0.8,
    baseMood: "confused",
  },
};
